name: IFILE Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branchs: [ master ]
jobs: 
  build: 
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 10
      - uses: actions/setup-node@v2
        with: 
          node-version: '10'
      - run: npm install
      